using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GIT_TEST_Project
{
    class Program
    {
        static void Main(string[] args)
        {
            /* DETTA ÄR EN JÄTTE VIKTIG TEXT LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM
             LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM
              LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM
               LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM
                LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM
                 LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM
                  LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM
                   LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM
                    LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM
                     LORUM IPSUM LORUM IPSUM LORUM IPSUM LORUM IPSUM*/

            
            Console.ReadLine();
            Car danielsBil = new Car();
        }
    }

    class Car
    {
        public int age { get; set; } = 4;
    }
}
